version: '3.8'
services:
  sqlserver:
    image: mcr.microsoft.com/mssql/server:2019-latest
    environment:
      - ACCEPT_EULA=Y
      - SA_PASSWORD=DB@password123
    ports:
      - 1433:1433
    volumes:
      - sqlserverdata:/var/opt/mssql
volumes:
  sqlserverdata:
