spring:
  datasource:
    url: jdbc:sqlserver://localhost:1433;databaseName=to_do_spring;trustServerCertificate=true
    username: sa
    password: DB@password123
    driverClassName: com.microsoft.sqlserver.jdbc.SQLServerDriver
  jpa:
    hibernate:
      ddl-auto: update
    database-platform: org.hibernate.dialect.SQLServer2012Dialect